---
title: "FinalShinyApp"
author: "Kelly and Debanjali"
date: "2024-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#getting necessary packages
library(shiny)
library(ggplot2)
library(dplyr)
library(tidyr)
library(shinydashboard)
library(ggrepel) # used to prevent label overlap in ggplots
library(plotly)

#cleaned dataset
cleaned_cancer_data <- read.csv("C:/Users/deban/OneDrive/Desktop/Docs/STA R Stuff/cleaned_cancer_data.csv")
```

## Building RShiny App
# Define UI
```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Cancer Data 2019"), # main heading in the app
  dashboardSidebar( # want 2 sidebar tabs for pie charts and line graphs
    sidebarMenu(
      menuItem("Pie Charts", tabName = "piechart", icon = icon("chart-pie")),
      menuItem("Line Graphs", tabName = "linegraph", icon = icon("chart-line"))
    )
  ),
  dashboardBody(
    tabItems(
      # First tab for Pie Chart
      tabItem(tabName = "piechart",
              h2("Pie Charts by Variable"),
              radioButtons(inputId = "pief", label = "Select Variable for Piechart:",
                           choiceNames = c("Age of Diagnosis", "Race/Ethnicity", "Sex", "Cancer Site"), # variable names available for selection
                           choiceValues = c("Age", "Race.ethnicity", "Sex", "Site")), # dataset columns
              actionButton("plot_button", "Show Updated Pie Chart"), # plot updates only when Button is clicked
              plotOutput("PieChart")
      ),
      
# Second tab for Line Graph
      tabItem(tabName = "linegraph",
              h2("Line Graph by Race/Ethnicity over Age groups"),
              radioButtons(inputId = "lines", label = "Select Race/Ethnicity:",
                           choiceNames = c("White", "Black", "All Asian", "All Pacific Islander",
                                           "American Indian/Alaska Native", "Other or Unknown"), # race/ethnicity types available for selection
                           choiceValues = c("White", "Black", "All Asian", "All Pacific Islander",
                                            "American Indian/Alaska Native", "Other or Unknown")),
              actionButton("plot_button", "Show Updated Line Graph"), # possible race/ethnicity types in dataset
              plotlyOutput("LineGraph")  # Updated to plotlyOutput to use hover later
      )
    )
  )
)

```

# Define server logic
```{r}
server <- function(input, output){
  # Data manipulation for pie-chart on cancer by race
  output$PieChart <- renderPlot({
    input$plot_button
    isolate({ #isolates this part of the code from running until update button is clicked
      # Create a summary based on the selected variable
      data <- cleaned_cancer_data %>%
        count(!!sym(input$pief)) %>%
        mutate(percent = n / sum(n) * 100,
               percent_label = paste0(round(percent, 1), "%"))
      
      # Plotting pie chart
      ggplot(data, aes(x = "", y = percent, fill = !!sym(input$pief))) +
        geom_col(color = "black") +
        coord_polar(theta = "y") +
        labs(fill = input$pief, y = "Percentage", x = NULL) +
        theme_minimal() +
        geom_text_repel(aes(label = percent_label), size = 4,
                        position = position_stack(vjust = 0.5),
                        box.padding = 0.05, max.overlaps = Inf) +
        scale_fill_brewer(palette = "Set3")
    })
  })
  
  # Data manipulation for line graphs on cancer by race/sex over age groups
  output$LineGraph <- renderPlotly({ # Use renderPlotly to allow hover
    input$plot_button
    isolate({
      data_count <- cleaned_cancer_data %>%
        filter(Race.ethnicity == input$lines) %>%
        group_by(Age, Sex) %>%
        summarise(count_perAgegroup = n(),
                  avg_survival_mts_perAgegroup = mean(Survival.months, na.rm = TRUE)) # want to display survival information in hover text
      
      # Custom hover text
      data_count <- data_count %>%
        mutate(hover_text = paste("Age Group:", Age, "<br>", # <br> puts a line break
                                  "Sex:", Sex, "<br>",
                                  "Count:", count_perAgegroup, "<br>",
                                  "Average Survival Months:", 
                                  round(avg_survival_mts_perAgegroup,1), "<br>"))
      
      # Plotting line graphs with custom hover text
      plot <- ggplot(data_count, aes(x = Age, 
                                     y = count_perAgegroup, 
                                     color = Sex, group = Sex, text = hover_text)) +
        geom_point() + geom_line() +
        labs(title = "Cancer Distribution Over Ages",
             x = "Age Group",
             y = "Count") +
        theme_minimal()
      
      ggplotly(plot, tooltip = "text")  # Displays custom hover text
    })
  })
}

# Run the app
shinyApp(ui, server)
```
